---
todo_dir: /tmp/todo
todo_file: /tmp/todo/todo.txt
done_file: /tmp/todo/done.txt
report_file: /tmp/todo/report.txt

remotes:
  # Can be more of them depending on hosted vs.
  # enterprise (elf-hosted)
  - name: github
    access_token: "secret"
    api_url: https://api.github.com/
    type: github
    ignore:
      - org1/*
      - org2/repo1
    add_context:
      - org1/*: foor
      - org2/*: bar
      - org2/repo: baz
  - name: gitlab
    access_token: "secret"
    api_url: https://gitlab.com/api/v4/
    type: gitlab
# NOTE: Supported types are: gitlab, github
