package com.denibertovic.todo.core.types

import com.denibertovic.todo.core.crdt.Operation
import com.denibertovic.todo.core.json.TodoJson
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe
import kotlinx.datetime.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Round-trip a JSON payload actually captured from the running
 * Haskell sync server. This is the acid test for wire-format
 * compatibility — if the Kotlin serializer drifts from Aeson's
 * output for any reason, this test fails loudly.
 *
 * The fixture lives under `src/test/resources/fixtures/` so it's
 * independent of the test source code and can be regenerated by
 * curling the server.
 */
@OptIn(ExperimentalUuidApi::class)
class HaskellFixtureTest : DescribeSpec({

    describe("add operation captured from Haskell server") {
        val json = javaClass.classLoader!!
            .getResourceAsStream("fixtures/add-op-from-haskell-server.json")!!
            .bufferedReader()
            .use { it.readText() }

        it("deserializes into Operation.Add with the expected fields") {
            val op = TodoJson.decodeFromString<Operation>(json) as Operation.Add
            op.opId shouldBe OperationId(Uuid.parse("df15d41c-2583-4c47-91d5-13eeb0fb8664"))
            op.itemId shouldBe ItemId(Uuid.parse("dc5141d6-8cea-40e4-99ff-378eadd259e3"))
            op.deviceId shouldBe DeviceId(Uuid.parse("37b303d6-51e9-42da-94bf-01425d4c85dd"))
            op.timestamp shouldBe Instant.parse("2026-04-11T12:00:00Z")
            op.item.priority shouldBe Priority.A
            op.item.description shouldBe "hello from android"
            op.item.metadata shouldBe listOf(Metadata.ProjectM(Project("todo")))
            op.item.createdAt shouldBe null
            op.item.completedAt shouldBe null
        }

        it("round-trips back into structurally-equivalent JSON") {
            val op = TodoJson.decodeFromString<Operation>(json)
            val re = TodoJson.encodeToString(Operation.serializer(), op)
            val lhs = TodoJson.parseToJsonElement(json)
            val rhs = TodoJson.parseToJsonElement(re)
            lhs shouldBe rhs
        }
    }
})
